### ISSUE TITLE
JSON Breaks on single quotes.

### ISSUE THREAD

**Issue by kingster** [APE-Project/APE_JSF#13]
missing ) after argument list

...raw":"data","data":{"msg":"<span style=\"color: #800\">I'm awesome!</span>"}}]'
----------------------------------------------------------------------------|

I am sending using php with the given example the line

```
"<span style=\"color: #800\">I'm awesome!</span>" 
```

**Comment by kingster** [comment]
I tried tracing the problem , but what all I could find is that when php encodes the json its fine

```
[
    {
        "cmd": "inlinepush",
        "params": {
            "password": "testpasswd",
            "raw": "data",
            "channel": "unlimited",
            "data": {
                "msg": "<span style=\"color: #080\">Hey, how are you doing?</span>"
            }
        }
    }
]
```

but when APE decodes it 
 ( i dumped the json) 

```
[
    {
        "time": "1340317629",
        "raw": "data",
        "data": {
            "msg": "<span style="color: #080">Hey, how are you doing?</span>"
        }
    }
]
```

Note I am using jsonp ( cross domain )

Any solutions?  I am stuck with this, normal text works fine but with html everything breaks! please help

**Comment by awysocki** [comment]
I came up with this work around.

$str = str_replace("'", "\u0027", "<span style=\"color: #800\">I'm awesome!</span>" );

so $str will look like

"<span style=\"color: #800\">I\u0027m awesome!</span>"

Convert all single quotes to \u0027,  not pretty but got me going
