### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by Head** [APE-Project/APE_JSF#3]
Like Nic said on http://www.ape-project.org/docs/client/client/load.html it is possible to join within the load() in the first request to multiple Channels:
load({channel: ['testchannel', 'broadcast']}

pls document it.
thx

**Comment by Xunnamius** [comment]
I second this (nearly a year later). If I hadn'tve happened to be trolling around github, I would've never picked up on this potentially-useful functionality!
