### ISSUE TITLE
Can't load APE JSF error, please help me out

### ISSUE THREAD

**Issue by ramesh-547** [APE-Project/APE_JSF#8]
Running test : Init
Running test : Loading Client
Running test : Loading config
Config values are :
identifier : ape
init : true
frequency : 0
scripts : http://example.com/ape-jsf/Source/mootools-core.js,http://example.com/ape-jsf/Source/Core/APE.js,http://example.com/ape-jsf/Source/Core/Events.js,http://example.com/ape-jsf/Source/Core/Core.js,http://example.com/ape-jsf/Source/Pipe/Pipe.js,http://example.com/ape-jsf/Source/Pipe/PipeProxy.js,http://example.com/ape-jsf/Source/Pipe/PipeMulti.js,http://example.com/ape-jsf/Source/Pipe/PipeSingle.js,http://example.com/ape-jsf/Source/Request/Request.js,http://example.com/ape-jsf/Source/Request/Request.Stack.js,http://example.com/ape-jsf/Source/Request/Request.CycledStack.js,http://example.com/ape-jsf/Source/Transport/Transport.longPolling.js,http://example.com/ape-jsf/Source/Transport/Transport.SSE.js,http://example.com/ape-jsf/Source/Transport/Transport.XHRStreaming.js,http://example.com/ape-jsf/Source/Transport/Transport.JSONP.js,http://example.com/ape-jsf/Source/Core/Utility.js,http://example.com/ape-jsf/Source/Core/JSON.js
baseUrl : http://example.com/ape-jsf
domain : example.com
server : ape.example.com:6969
Running test : Setting document.domain
Running test : Checking APE.Config.baseUrl
APE JSF Version 1.0
Running test : Contacting APE Server
domain = example.com
Running test : Contacting APE Server (adding frequency)
Running test : Initializing APE Client
Can't load APE JSF
Something went wrong. If you can't fix it by yourself post a message on the newsgroups with the output below or join our IRC channel

**Comment by berighton** [comment]
I am experiencing the same issue:

Running test : Init
Running test : Loading Client
Running test : Loading config
Config values are :

identifier : ape
init : true
frequency : 0
scripts : https://example.com/ape/Source/mootools-core.js,https://example.com/ape/Source/Core/APE.js,https://example.com/ape/Source/Core/Events.js,https://example.com/ape/Source/Core/Core.js,https://example.com/ape/Source/Pipe/Pipe.js,https://example.com/ape/Source/Pipe/PipeProxy.js,https://example.com/ape/Source/Pipe/PipeMulti.js,https://example.com/ape/Source/Pipe/PipeSingle.js,https://example.com/ape/Source/Request/Request.js,https://example.com/ape/Source/Request/Request.Stack.js,https://example.com/ape/Source/Request/Request.CycledStack.js,https://example.com/ape/Source/Transport/Transport.longPolling.js,https://example.com/ape/Source/Transport/Transport.SSE.js,https://example.com/ape/Source/Transport/Transport.XHRStreaming.js,https://example.com/ape/Source/Transport/Transport.JSONP.js,https://example.com/ape/Source/Transport/Transport.WebSocket.js,https://example.com/ape/Source/Core/Utility.js,https://example.com/ape/Source/Core/JSON.js
baseUrl : https://example.com/ape
domain : example.com
server : ape.example.com:6969

Running test : Setting document.domain
Running test : Checking APE.Config.baseUrl
APE JSF Version 1.0
Running test : Contacting APE Server
domain = example.com
Running test : Contacting APE Server (adding frequency)
Running test : Initializing APE Client
Can't load APE JSF

Here's what I have in my Demo/config.js:

APE.Config.baseUrl = 'https://example.com/ape'; //APE JSF
APE.Config.domain = 'example.com';
APE.Config.server = 'ape.example.com:6969'; //APE server URL

(function(){
    for (var i = 0; i < arguments.length; i++)
        APE.Config.scripts.push(APE.Config.baseUrl + '/Source/' + arguments[i] + '.js');
})('mootools-core', 'Core/APE', 'Core/Events', 'Core/Core', 'Pipe/Pipe', 'Pipe/PipeProxy', 'Pipe/PipeMulti', 'Pipe/PipeSingle', 'Request/Request','Request/Request.Stack', 'Request/Request.CycledStack', 'Transport/Transport.longPolling','Transport/Transport.SSE', 'Transport/Transport.XHRStreaming', 'Transport/Transport.JSONP', 'Transport/Transport.WebSocket', 'Core/Utility', 'Core/JSON');

Please help me, I am not sure what else is going wrong. The server domain is valid as this config tool is able to find it and connect. The domain and baseUrl are valid too. But APE JSF fails. 

Thanks.
